environment                           = "sandbox-hpc"
is_staging                            = false
is_production                         = false
waf_logs_bucket_name                  = "aws-waf-logs-sandboxhpc-ce4f2"
nlb_logs_bucket_name                  = "public-nlb-access-logs-obp-sandbox-hpc"
primary_domain_name                   = "sandboxhpc.openbraininstitute.org"
email_domain_name                     = "sandboxhpc.openbraininstitute.org"
alt_domain_openbluebrain_com_name     = "sandboxhpc.openbluebrain.com"
alt_domain_openbrainplatform_com_name = "sandboxhpc.openbrainplatform.com"
alt_domain_openbrainplatform_org_name = "sandboxhpc.openbrainplatform.org"
domain_openbraininstitute_org_name    = "sandboxhpc.openbraininstitute.org"
domain_openbraininstitute_com_name    = "sandboxhpc.openbraininstitute.com"
domain_openbraininstitute_ch_name     = "sandboxhpc.openbraininstitute.ch"
web_logs_athena_workgroup_bucket_name = "web-logs-athena-workgroup-obi-sandbox-hpc"

vpn2_to_azure_enabled                  = false
vpn_to_azure_aws_bgp_asn               = -1
azure_bgp_asn2                         = -1
azure_vpn_gateway_tunnel2_inside_cidr1 = "not enabled"
azure_vpn_gateway_tunnel2_inside_cidr2 = "not enabled"
vpn_customer_gw2_name                  = "not enabled"
vpn2_conn_name                         = "not enabled"
tunnel2_ike_log_group1_name            = "not enabled"
tunnel2_ike_log_group2_name            = "not enabled"
tunnel2_bgp_log_group1_name            = "not enabled"
tunnel2_bgp_log_group2_name            = "not enabled"
