environment                           = "sandbox-nse"
waf_logs_bucket_name                  = "aws-waf-logs-sandboxnse-6ba52"
nlb_logs_bucket_name                  = "public-nlb-access-logs-obp-sandbox-nse"
primary_domain_name                   = "sandboxnse.openbraininstitute.org"
email_domain_name                     = "sandboxnse.openbraininstitute.org"
alt_domain_openbluebrain_com_name     = "sandboxnse.openbluebrain.com"
alt_domain_openbrainplatform_com_name = "sandboxnse.openbrainplatform.com"
alt_domain_openbrainplatform_org_name = "sandboxnse.openbrainplatform.org"
domain_openbraininstitute_org_name    = "sandboxnse.openbraininstitute.org"
domain_openbraininstitute_com_name    = "sandboxnse.openbraininstitute.com"
domain_openbraininstitute_ch_name     = "sandboxnse.openbraininstitute.ch"
web_logs_athena_workgroup_bucket_name = "web-logs-athena-workgroup-obi-sandbox-nse"

vpn2_to_azure_enabled                  = false
vpn_to_azure_aws_bgp_asn               = -1
azure_bgp_asn2                         = -1
azure_vpn_gateway_tunnel2_inside_cidr1 = "not enabled"
azure_vpn_gateway_tunnel2_inside_cidr2 = "not enabled"
vpn_customer_gw2_name                  = "not enabled"
vpn2_conn_name                         = "not enabled"
tunnel2_ike_log_group1_name            = "not enabled"
tunnel2_ike_log_group2_name            = "not enabled"
tunnel2_bgp_log_group1_name            = "not enabled"
tunnel2_bgp_log_group2_name            = "not enabled"
