name: Auto - Check DNS records for TLS certificates - Staging

env:
  AWS_ROLE_ARN_STAGING: arn:aws:iam::992382665735:role/GithubTerraformDeployCommon

# For staging, only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches:
      - staging

jobs:
  dns_check:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    environment: ${{ github.base_ref }}
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    name: Auto Check DNS records for validation of TLS certificates
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN_STAGING }}
          aws-region: us-east-1

      - name: Make script executable
        run: chmod +x .github/scripts/check_dns_records_for_certificates.sh

      - name: Run the script
        run: .github/scripts/check_dns_records_for_certificates.sh

