name: Auto - Apply changes on Merge to staging

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches:
      - staging

env:
  AWS_ROLE_ARN_STAGING: arn:aws:iam::992382665735:role/GithubTerraformDeployCommon
  AWS_ROLE_ARN_PRODUCTION: arn:aws:iam::671250183987:role/GithubTerraformDeployCommon

jobs:
  terraform_apply:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    environment: ${{ github.base_ref }}
    permissions:
      id-token: write
      contents: read
    env:
      #TF_VAR_azure_vpn_gateway_tunnel1_preshared_key1: ${{ secrets.AZURE_VPN_GATEWAY_PRESHARED_KEY1 }}
      #TF_VAR_azure_vpn_gateway_tunnel1_preshared_key2: ${{ secrets.AZURE_VPN_GATEWAY_PRESHARED_KEY2 }}
      #TF_VAR_azure_vpn_gateway_tunnel1_ip_address: ${{ secrets.AZURE_VPN_GATEWAY_TUNNEL1_IP_ADDRESS }}
      TF_VAR_azure_vpn_gateway_tunnel2_preshared_key1: ${{ secrets.AZURE_VPN_GATEWAY_PRESHARED_KEY3 }}
      TF_VAR_azure_vpn_gateway_tunnel2_preshared_key2: ${{ secrets.AZURE_VPN_GATEWAY_PRESHARED_KEY4 }}
      TF_VAR_azure_vpn_gateway_tunnel2_ip_address: ${{ secrets.AZURE_VPN_GATEWAY_TUNNEL2_IP_ADDRESS }}


    runs-on: ubuntu-latest
    name: Auto Apply terraform code to staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN_STAGING }}
          aws-region: us-east-1

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init -backend-config="./${{ github.base_ref }}.config"

      - name: Run Terraform Apply
        run: |
          terraform apply -auto-approve -var-file="${{ github.ref_name }}.tfvars"
