name: Terraform deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment name'
        required: true

jobs:
  terraform_deployment:
    environment: ${{ inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: ubuntu-latest
    name: Run terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init -backend-config="./${{ inputs.environment }}.config"

      - name: Run Terraform Plan
        run: |
          terraform plan -var="environment=${{ inputs.environment }}"

      #- name: Run Terraform Apply
      #  run: |
      #    terraform apply -auto-approve -var="environment=${{ inputs.environment }}"
