name: Terraform deployment
on:
  workflow_dispatch:

jobs:
  terraform_deployment:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENVIRONMENT: ${{ github.head_ref || github.ref_name }} # use branch name as deployment environment

    runs-on: ubuntu-latest
    name: Run terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init -backend-config="./$ENVIRONMENT.config"

      - name: Run Terraform Plan
        run: |
          terraform plan -var="environment=$ENVIRONMENT"

      #- name: Run Terraform Apply
      #  run: |
      #    terraform apply -auto-approve -var="environment=$ENVIRONMENT
